apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
spec:
  restartPolicy: Never
  containers:
  - name: hello-world
    image: hw:latest
    imagePullPolicy: Never
    env:
    - name: HELLO_WHAT
      value: The Great Beyond
