apiVersion: v1
kind: Pod
metadata:
  name: client-env-pod
spec:
  restartPolicy: Never
  containers:
  - name: client
    image: client:latest
    imagePullPolicy: Never
    command: ["python", "-m", "client"]

