apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    app: hello-world
spec:
  containers:
  - name: hw
    image: hw:latest
    imagePullPolicy: Never
    volumeMounts:
    - mountPath: /data
      name: hello-volume
  volumes:
  - name: hello-volume
    hostPath:
      path: /tmp/hello-data
      type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8080

